service: sls-services-snippet
frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, "ap-northeast-1"}
  memorySize: 256
  timeout: 30
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'secretsmanager:GetSecretValue'
            - 'ssm:GetParameter'
            - 'sts:AssumeRole'
            - 'ec2:DescribeSecurityGroups'
            - 'ec2:DescribeRegions'
          Resource:
            - '*'
  environment: ${self:custom.environment.${self:provider.stage}}
functions:
  setup_iam:
    handler: src/handlers/setup_iam.handler
custom:
  environment:
    dev:
      STAGE: ${self:provider.stage}
    stg:
      STAGE: ${self:provider.stage}
    prod:
      STAGE: ${self:provider.stage}
  pythonRequirements:
    usePipenv: true
  prune:
    automatic: true
    number: 3
plugins:
  - serverless-step-functions
  - serverless-python-requirements
  - serverless-prune-plugin
# stepFunctions: ${file(includes/state-machines.yml)}
package:
  patterns:
    - "!./**"
    - ./src/**/*.py
