service: template-sls
frameworkVersion: "2"
provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, "ap-northeast-1"}
  memorySize: 256
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
        - "ssm:GetParameter"
        - "sts:AssumeRole"
      Resource:
        - "*"
functions:
  hello:
    handler: src/handlers/handler.hello
custom:
  environment:
    dev:
      STAGE: ${self:provider.stage}
    stg:
      STAGE: ${self:provider.stage}
    prod:
      STAGE: ${self:provider.stage}
  prune:
    automatic: true
    number: 3
plugins:
  - serverless-step-functions
  - serverless-python-requirements
  - serverless-prune-plugin
stepFunctions: ${file(includes/state-machines.yml)}
package:
  patterns:
    - "!./**"
    - ./src/**/*.py
